# Generated by Django 5.2.13 on 2026-04-13 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionableEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes')),
                ('focus_score', models.IntegerField(blank=True, help_text='Subjective score 1-10', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
