# Generated by Django 5.2.13 on 2026-04-13 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegimeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, unique=True)),
                ('regime_label', models.CharField(db_index=True, max_length=30)),
                ('regime_score', models.FloatField(default=0.0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='ActivityEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.TextField()),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('predicted_class', models.CharField(db_index=True, max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('used_fallback', models.BooleanField(default=False)),
                ('cluster_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('classifier_version', models.CharField(default='phase2-v1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_record', to='intelligence.actionableevent')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
