# Generated by Django 5.2.13 on 2026-04-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_regimesnapshot_activityembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('predicted_uplift', models.FloatField(default=0.0)),
                ('reward', models.FloatField(blank=True, null=True)),
                ('accepted', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
