# Generated by Django 5.2.13 on 2026-04-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0003_interventionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitInfluenceEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_label', models.CharField(db_index=True, max_length=255)),
                ('target_label', models.CharField(db_index=True, max_length=255)),
                ('weight', models.FloatField(default=0.0)),
                ('transition_count', models.IntegerField(default=0)),
                ('avg_gap_minutes', models.FloatField(default=0.0)),
                ('positive_impact', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-weight'],
                'unique_together': {('source_label', 'target_label')},
            },
        ),
    ]
